# Generated by Django 3.2.8 on 2021-10-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Muster',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='Muster_2',
        ),
    ]
